version: '3.5'

services:
  # redis:
  #   image: redis:latest
  #   ports:
  #     - "6379:6379"
  database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '33068:3306'
    environment: 
      - "MYSQL_ROOT_PASSWORD=secret"
      - "MYSQL_DATABASE=countryapp"

  app:
    image: 'countryapp:latest'
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html/
    ports: 
      - '8050:80'
    environment: 
      - "DB_HOST=database"
      - 'XDEBUG_CONFIG="remote_host=host.docker.internal remote_enable=1"'
    depends_on:
      - database
      # - redis
      
  adminer:
    image: adminer
    # restart: always
    environment:
      - "ADMINER_DEFAULT_SERVER=database"
    ports:
      - 8080:8080