version: '3.5'

services:
  database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '33068:3306'
    environment: 
      - "MYSQL_ROOT_PASSWORD=secret"
      - "MYSQL_DATABASE=countryapp"

  app:
    image: 'countryapp:latest'
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html/
      # - php.ini/:/usr/local/etc/php/php.ini
      # - php.ini/:/usr/local/etc/php/conf.d/xdebug.ini
    ports: 
      - '8050:80'
      - '9000:9000'
    environment: 
      - "DB_HOST=database"
      - 'XDEBUG_CONFIG="remote_host=host.docker.internal"'
    depends_on:
      - database
      
  adminer:
    image: adminer
    # restart: always
    environment:
      - "ADMINER_DEFAULT_SERVER=database"
    ports:
      - 8080:8080